### PR TITLE
Collect snippets, update AWSTypes with latest API

### PR DESCRIPTION
**Pull request by thecarlhall**
There's a lot in this PR.  I'd be happy to split it up if you want.

I started by running `aws_dl.py` to update AWSTypes with the latest APIs.  I later added to that script the ability to scrape the example code from the same documentation and convert it into snippets.  The short names for the snippets has some collisions that might need to be worked out.

### CODE REVIEW

**Comment by andrewstuart** [comment]
Haha, I get the distinct feeling we may not be getting our PRs merged for a while.

**Comment by dopeghoti** [comment]
You may be right.

**Comment by m-kat** [comment]
~thx guys for contributing, sorry for late merges, but I forgot about this plugin to maintain it.

**Comment by andrewstuart** [comment]
Sweet! Better late than never. Thanks!

**Pull request merged**
